using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace BeamFlow.AppAdsTxt
{
    /// <summary>
    /// Generates the complete app-ads.txt file content from detected networks,
    /// publisher IDs, and optional BeamFlow managed lines.
    /// </summary>
    public static class LineGenerator
    {
        /// <summary>
        /// Generate the complete app-ads.txt content.
        /// </summary>
        /// <param name="enabledNetworks">Network IDs that should be included.</param>
        /// <param name="publisherIds">Publisher ID per network (key = network ID, value = publisher ID).</param>
        /// <param name="apiLines">Additional lines from BeamFlow API (optional, can be null).</param>
        /// <returns>The complete file content as a string.</returns>
        public static string Generate(
            List<string> enabledNetworks,
            Dictionary<string, string> publisherIds,
            List<string> apiLines = null)
        {
            var sb = new StringBuilder();
            var seenLines = new HashSet<string>();

            sb.AppendLine("# app-ads.txt generated by BeamFlow App-Ads.txt Manager");
            sb.AppendLine("# https://beamflow.co");
            sb.AppendLine();

            foreach (var networkId in enabledNetworks)
            {
                var templateLines = NetworkTemplates.GetLines(networkId);
                if (templateLines.Count == 0)
                    continue;

                // Get publisher ID for this network (if needed)
                publisherIds.TryGetValue(networkId, out var pubId);
                pubId = string.IsNullOrWhiteSpace(pubId) ? "" : pubId.Trim();

                // Get display name
                var displayName = GetNetworkDisplayName(networkId);
                sb.AppendLine($"# {displayName}");

                foreach (var template in templateLines)
                {
                    var line = template;

                    // Replace publisher ID placeholder
                    if (line.Contains("{PUBLISHER_ID}"))
                    {
                        if (string.IsNullOrEmpty(pubId))
                            continue; // Skip lines that need a publisher ID but don't have one
                        line = line.Replace("{PUBLISHER_ID}", pubId);
                    }

                    // Deduplicate
                    var normalized = line.Trim().ToLowerInvariant();
                    if (seenLines.Contains(normalized))
                        continue;

                    seenLines.Add(normalized);
                    sb.AppendLine(line);
                }

                sb.AppendLine();
            }

            // Append BeamFlow managed lines (from API)
            if (apiLines != null && apiLines.Count > 0)
            {
                sb.AppendLine("# BeamFlow Managed Lines");
                foreach (var line in apiLines)
                {
                    var normalized = line.Trim().ToLowerInvariant();
                    if (!seenLines.Contains(normalized))
                    {
                        seenLines.Add(normalized);
                        sb.AppendLine(line.Trim());
                    }
                }
                sb.AppendLine();
            }

            return sb.ToString().TrimEnd() + "\n";
        }

        /// <summary>
        /// Count the total number of non-comment, non-empty lines in generated content.
        /// </summary>
        public static int CountDataLines(string content)
        {
            if (string.IsNullOrEmpty(content)) return 0;
            return content.Split('\n')
                .Count(l => !string.IsNullOrWhiteSpace(l) && !l.TrimStart().StartsWith("#"));
        }

        private static string GetNetworkDisplayName(string networkId)
        {
            switch (networkId)
            {
                case "admob": return "Google AdMob";
                case "applovin": return "AppLovin MAX";
                case "unity_ads": return "Unity Ads / LevelPlay";
                case "ironsource": return "ironSource";
                case "meta": return "Meta Audience Network";
                case "vungle": return "Vungle / Liftoff";
                case "chartboost": return "Chartboost";
                case "inmobi": return "InMobi";
                case "mintegral": return "Mintegral";
                case "pangle": return "Pangle (TikTok)";
                case "dt_exchange": return "Digital Turbine / Fyber";
                case "amazon_aps": return "Amazon Publisher Services";
                default: return networkId;
            }
        }
    }
}
